#!/usr/bin/env bash
# Used by .github/workflows/daily-digest.yml — gathers PRs/issues, builds digest (AI or fallback),
# writes GitHub Actions job summary, optional GitHub Discussion, optional Slack.
set -euo pipefail

: "${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"
: "${GITHUB_REPOSITORY_OWNER:?GITHUB_REPOSITORY_OWNER is required}"
: "${GITHUB_STEP_SUMMARY:?GITHUB_STEP_SUMMARY is required}"

REPO_NAME="${GITHUB_REPOSITORY##*/}"
REPO="${GITHUB_REPOSITORY}"
export GH_TOKEN="${GH_TOKEN:?GH_TOKEN is required}"

gh pr list --repo "${REPO}" --state open \
  --json number,title,author,createdAt,reviewDecision,url,labels,isDraft \
  --limit 80 > /tmp/prs.json

gh issue list --repo "${REPO}" --state open \
  --json number,title,labels,assignees,createdAt,url \
  --limit 80 > /tmp/issues.json

if [[ -n "${ANTHROPIC_API_KEY:-}" ]]; then
  SYSTEM_PROMPT=$(cat .github/prompts/daily-digest.md)
  REQUEST_JSON=$(jq -n \
    --arg system "${SYSTEM_PROMPT}" \
    --rawfile prs /tmp/prs.json \
    --rawfile issues /tmp/issues.json \
    '{
      model: "claude-sonnet-4-20250514",
      max_tokens: 2048,
      system: $system,
      messages: [{
        role: "user",
        content: (
          "Open pull requests (JSON array):\n" + $prs +
          "\n\nOpen issues (JSON array):\n" + $issues
        )
      }]
    }')

  RESPONSE=$(curl -sS https://api.anthropic.com/v1/messages \
    -H "content-type: application/json" \
    -H "x-api-key: ${ANTHROPIC_API_KEY}" \
    -H "anthropic-version: 2023-06-01" \
    -d "${REQUEST_JSON}")

  echo "${RESPONSE}" | jq -e '.content[0].text' -r > /tmp/digest.md || {
    echo "::error::Anthropic API returned an unexpected response"
    echo "${RESPONSE}" | head -c 2000
    exit 1
  }

  {
    echo "## Daily digest (AI)"
    echo
    cat /tmp/digest.md
    echo
    echo "---"
    echo "*Generated by workflow using Anthropic. Review for accuracy.*"
  } > /tmp/digest-with-footer.md
  mv /tmp/digest-with-footer.md /tmp/digest.md
else
  PRS_MD=$(jq -r '
    if length == 0 then "_No open pull requests._"
    else map(
      (if .isDraft then "**[Draft]** " else "" end) +
      "[#\(.number) \(.title)](\(.url)) — \(.author.login // "unknown")"
    ) | map("- " + .) | join("\n")
    end
  ' /tmp/prs.json)

  ISSUES_MD=$(jq -r '
    if length == 0 then "_No open issues._"
    else map("- [#\(.number) \(.title)](\(.url))") | join("\n")
    end
  ' /tmp/issues.json)

  cat > /tmp/digest.md <<EOF
## Daily digest (fallback)

_No \`ANTHROPIC_API_KEY\` secret — showing a simple list. Add the secret for an AI-generated summary._

### Open pull requests

${PRS_MD}

### Open issues

${ISSUES_MD}

### Today's recommendation

- Triage open issues and review open PRs in order of age.
- Add \`ANTHROPIC_API_KEY\` under **Settings → Secrets and variables → Actions** for a richer digest.
EOF
fi

{
  echo "## Daily digest"
  echo
  cat /tmp/digest.md
} >> "${GITHUB_STEP_SUMMARY}"

post_discussion() {
  local repo_id cat_id title date_utc
  date_utc=$(date -u +%Y-%m-%d)
  title="Daily digest — ${date_utc}"

  repo_id=$(gh api graphql \
    -f query='query($o:String!,$n:String!){repository(owner:$o,name:$n){id}}' \
    -f o="${GITHUB_REPOSITORY_OWNER}" \
    -f n="${REPO_NAME}" \
    --jq '.data.repository.id' 2>/dev/null || true)

  if [[ -z "${repo_id}" || "${repo_id}" == "null" ]]; then
    echo "::warning::Could not resolve repository id; skipping Discussion."
    return 0
  fi

  cat_id=$(gh api graphql \
    -f query='query($o:String!,$n:String!){repository(owner:$o,name:$n){discussionCategories(first:15){nodes{id name}}}}' \
    -f o="${GITHUB_REPOSITORY_OWNER}" \
    -f n="${REPO_NAME}" \
    --jq '.data.repository.discussionCategories.nodes[] | select(.name=="General") | .id' 2>/dev/null | head -1)

  if [[ -z "${cat_id}" ]]; then
    cat_id=$(gh api graphql \
      -f query='query($o:String!,$n:String!){repository(owner:$o,name:$n){discussionCategories(first:15){nodes{id name}}}}' \
      -f o="${GITHUB_REPOSITORY_OWNER}" \
      -f n="${REPO_NAME}" \
      --jq '.data.repository.discussionCategories.nodes[0].id' 2>/dev/null || true)
  fi

  if [[ -z "${cat_id}" || "${cat_id}" == "null" ]]; then
    echo "::warning::No Discussion categories found. Enable **Discussions** under repository Settings and use a **General** category (or any category). Skipping Discussion post."
    return 0
  fi

  jq -n \
    --arg repositoryId "${repo_id}" \
    --arg categoryId "${cat_id}" \
    --arg title "${title}" \
    --rawfile body /tmp/digest.md \
    '{
      query: "mutation($repositoryId: ID!, $categoryId: ID!, $title: String!, $body: String!) { createDiscussion(input: {repositoryId: $repositoryId, categoryId: $categoryId, title: $title, body: $body}) { discussion { url } } }",
      variables: {
        repositoryId: $repositoryId,
        categoryId: $categoryId,
        title: $title,
        body: $body
      }
    }' > /tmp/digest-graphql.json

  DISCUSSION_URL=""
  if ! DISCUSSION_URL=$(gh api graphql --input /tmp/digest-graphql.json --jq '.data.createDiscussion.discussion.url // empty' 2>/dev/null); then
    echo "::warning::createDiscussion GraphQL request failed (check Discussions are enabled and token has discussions: write)."
    return 0
  fi

  if [[ -n "${DISCUSSION_URL}" ]]; then
    echo "::notice::Discussion created: ${DISCUSSION_URL}"
    echo "Posted to Discussion: ${DISCUSSION_URL}" >> "${GITHUB_STEP_SUMMARY}"
  else
    echo "::warning::createDiscussion did not return a URL (check Discussions permissions and categories)."
  fi
}

post_discussion

post_slack() {
  [[ -n "${SLACK_WEBHOOK_URL:-}" ]] || return 0

  local slack_text
  slack_text=$(head -c 12000 /tmp/digest.md)
  if [[ "$(wc -c < /tmp/digest.md)" -gt 12000 ]]; then
    slack_text="${slack_text}

_(Truncated for Slack — see the full digest in GitHub Actions job summary or the Discussion.)_"
  fi

  HTTP_CODE=$(jq -n --arg text "${slack_text}" '{text: $text}' | curl -sS -o /tmp/slack-response.txt -w "%{http_code}" -X POST \
    -H 'Content-type: application/json; charset=utf-8' \
    --data-binary @- \
    "${SLACK_WEBHOOK_URL}")
  if [[ "${HTTP_CODE}" != "200" ]]; then
    echo "::warning::Slack webhook returned HTTP ${HTTP_CODE}"
  else
    echo "::notice::Posted digest to Slack incoming webhook."
    echo "Posted copy to Slack (truncated if long)." >> "${GITHUB_STEP_SUMMARY}"
  fi
}

post_slack
